### PR TITLE
Add OS X flatbuffers-compiler binaries

### PR DESCRIPTION
**Pull request by frew**
This is my first time creating this kind of native Maven package, so please let me know if I overlooked anything. Tested by building examples with the OS X classifier (the change reverted by the second commit) - happy to do any other testing that would make sense.

### CODE REVIEW

**Comment by frew** [comment]
@davidmoten Are you interested in this patch or should I release the OS X version under a different group ID? No worries either way - just let me know which works best for you.

**Comment by davidmoten** [comment]
Sorry forgot yep I can release

**Comment by davidmoten** [comment]
hmm wait a sec which of these binaries are actually needed?

```flatc  flathash  flatsamplebinary  flatsampletext  flattests  libflatbuffers.a```

Surely we can turf the `*sample*` and perhaps `flattests`? What is `flathash`?

I'll wait for your info before building an artifact.

**Comment by frew** [comment]
Yeah - I think you can delete everything except flatc. I was matching the linux dir, which has all of those binaries, but windows only has flatc and the compiler doesn't seem to rely on any of the other files.

**Comment by davidmoten** [comment]
Righto I'll delete the other binaries and release, thanks @frew

**Comment by davidmoten** [comment]
Released to Maven Central (should be downloadable in 15 minutes or so), updated README.md.

**Pull request merged**
