### PR TITLE
Updated to work with flatbuffers 1.12.0

### PR DESCRIPTION
**Pull request by mdaley**
I've updated so that things work with flatbuffers 1.12.0.  Compilation and testing works on linux (ubuntu in my case) and on OSX (changing to use distribution-osx first though).  Don't know about Windows though even though new release exe included.

Just wondering though, is this a project that people use or should I be going elsewhere? Just wondering because prior to this there haven't been any changes since the end of 2018.

### CODE REVIEW

**Comment by davidmoten** [comment]
Yep still supporting this, thanks for the contribution.

What version of ubuntu did you use to do the compilation of binaries? I recall it being a good idea not to aim too high in versions so that older versions of linux didn't have problems

Accepting binaries in the PR is a a bit of security risk don't you think? Perhaps exclude them for the moment and I'll build the binaries (I become the security risk instead!). However, I'm in a pickle with the OSX binary because I don't have access to OSX. Any suggestions on establishing the trust relationship necessary to have other parties build a binary?

**Comment by mdaley** [comment]
Hi David, I used a VM of Ubuntu 18.04, which is a recent version.  I guess either you or I could build the binaries on an earlier version.  Also, I work on a macbook so it is easy for me to build on that.  I don't know whether there are similar 'version' related problems for macs.

I understand your issues with the security of binaries.  It would be much better if the build could pull in binaries from an original trusted source.  It's a pity that the Google project doesn't publish all the binaries.  It's a pity that they don't have a maven dependency for the Java classes that they generate.  I can imagine it being possible to pull down their repository do various builds, perhaps in VMs, to get the different OS executables, build the Java side and then plug it all together.  But, that would be a big job! 

I guess there are limits to what is practical though.  

I am happy to be guided by you in how you want to play it and am willing to help by changing the PR, building things etc...

For the moment I've got a local snapshot and am managing to use it successfully in a project I'm working on.  Thanks for creating it!

**Comment by mdaley** [comment]
I tried the flatc executable on an earlier version of linux, ubuntu 16.04.6 which is the oldest, still supported LTS version, and it works fine.  Didn't work on Centos 6 though.   I guess it's pretty hard to create a fully portable version so I guess that's why google don't provide binaries.  Perhaps a better answer is to tell the user to install flatbuffers and build the binaries and then to have an environment variable to point at them.

**Comment by mdaley** [comment]
Yes, you build the exes :-(. My `flatc` doesn't work on Centos 7 either.

I guess `flatc` is only required at compile time.  Perhaps it's really better to get the user to built it separately and for this library to reference it.  That avoids security worries too.

**Comment by davidmoten** [comment]
>I guess flatc is only required at compile time. Perhaps it's really better to get the user to built it separately and for this library to reference it. That avoids security worries too.

Still a pain in the ass for people to stuff around with it all. I'll build on ubuntu 16.04 and should work for most out there.

Can you remove the linux binaries from your PR? I'll merge and build them myself. The OSX binaries I'm grateful for because I can't build them.

**Comment by mdaley** [comment]
OK, I've removed the linux executables.  

Hmm... this is interesting.  I've just discovered this:
```
<dependency>
            <groupId>com.google.flatbuffers</groupId>
            <artifactId>flatbuffers-java</artifactId>
            <version>1.12.0</version>
        </dependency>
```
Looks like the flatbuffers project now has pom at its root sed to build this library.  It is exactly the same as your flatbuffers-java.  Drop in replacement works fine.  So, I would say that perhaps what this project should focus a jar that wraps flatc executables for the maven build process.

Still might as well merge and complete what I've done though.

**Comment by mdaley** [comment]
I've been working on an alternative plugin.  See what you think here:

https://github.com/sequsoft/flatbuffers-maven-plugin

**Comment by davidmoten** [comment]
Looks like a nice job @mdaley. Very hopeful for those that want to compile themselves. 

Would you mind removing the linux executables from this PR? I'll merge and build.

**Comment by mdaley** [comment]
Hmm... the linux exes have been removed.  Well, I think so.  Are you not seeing that?

**Comment by davidmoten** [comment]
@mdaley, thanks for contributing, I've released 1.12.0.1 to Maven Central. Linux binaries built using ubuntu 16.04 so should work for most.

**Pull request merged**
